package com.okta.springbootmongo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import reactor.core.publisher.Flux;


@Controller
@RequestMapping(path="/kayak")
public class KayakController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private KayakRepository kayakRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser (
            @RequestParam String name,
            @RequestParam String owner,
            @RequestParam Number value,
            @RequestParam String makeModel
    ) {
        Kayak kayak = new Kayak(name, owner, value, makeModel);
        kayakRepository.save(kayak);
        return "Saved";
        
    }

    @GetMapping(path="/all")
    public @ResponseBody
    Flux<Kayak> getAllUsers() {
        Flux<Kayak> result = kayakRepository.findAll();
        return result;
    }
    
}