package com.okta.springbootmongo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import reactor.core.publisher.Flux;


@Controller
@RequestMapping(path="/account")
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountMongoRepository;

    @GetMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name, @RequestParam String email) {


        Account acct = new Account(name, email);
        accountMongoRepository.save(acct);
        return "Saved";
        
    }

    @GetMapping(path="/all")
    public @ResponseBody
    Flux<Account> getAllUsers() {
        Flux<Account> result = accountMongoRepository.findAll();
        return result;
    }
}